#!/bin/sh

if [ "$NODE_ENV" = 'development' ]; then
  npm install
else
  npm install --production
  echo "Compiling assets"
  browserify client/index.js -o public/javascripts/index.js
  browserify client/admin.js -o public/javascripts/admin.js
fi
