#!/bin/sh

if [[ -z $NODE_ENV ]]; then
  export NODE_ENV=development
fi

script/bootstrap

if [ "$NODE_ENV" = 'development' ]; then
  echo "Running Print Queue in Development"
  watchify client/*.js -o public/javascripts/main.js -v & nodemon -e js,handlebars app.js
else
  node app.js
fi
