#!/bin/bash

if [[ -z $NODE_ENV ]]; then
  export NODE_ENV=development
fi

script/bootstrap

if [ "$NODE_ENV" = 'development' ]; then
  echo "Running Print Queue in Development"
  watchify client/index.js -o public/javascripts/index.js -v & watchify client/admin.js -o public/javascripts/admin.js -v & nodemon -e js,handlebars app.js
else
  node app.js
fi
